/*
 * Top Stories V2
 * The Top Stories API provides JSON and JSONP lists of articles and associated images by section.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ArticleRelatedUrls
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-19T22:13:55.972-04:00")
public class ArticleRelatedUrls   {
  @SerializedName("suggested_link_text")
  private String suggestedLinkText = null;

  @SerializedName("url")
  private String url = null;

  public ArticleRelatedUrls suggestedLinkText(String suggestedLinkText) {
    this.suggestedLinkText = suggestedLinkText;
    return this;
  }

   /**
   * Get suggestedLinkText
   * @return suggestedLinkText
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuggestedLinkText() {
    return suggestedLinkText;
  }

  public void setSuggestedLinkText(String suggestedLinkText) {
    this.suggestedLinkText = suggestedLinkText;
  }

  public ArticleRelatedUrls url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleRelatedUrls articleRelatedUrls = (ArticleRelatedUrls) o;
    return Objects.equals(this.suggestedLinkText, articleRelatedUrls.suggestedLinkText) &&
        Objects.equals(this.url, articleRelatedUrls.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suggestedLinkText, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleRelatedUrls {\n");
    
    sb.append("    suggestedLinkText: ").append(toIndentedString(suggestedLinkText)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

