/*
 * Top Stories V2
 * The Top Stories API provides JSON and JSONP lists of articles and associated images by section.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ArticleMultimedia;
import io.swagger.client.model.ArticleRelatedUrls;
import java.util.ArrayList;
import java.util.List;


/**
 * Article
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-20T08:32:43.573-04:00")
public class Article   {
  @SerializedName("section")
  private String section = null;

  @SerializedName("subsection")
  private String subsection = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("abstract")
  private String _abstract = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("thumbnail_standard")
  private String thumbnailStandard = null;

  @SerializedName("short_url")
  private String shortUrl = null;

  @SerializedName("byline")
  private String byline = null;

  @SerializedName("item_type")
  private String itemType = null;

  @SerializedName("updated_date")
  private String updatedDate = null;

  @SerializedName("created_date")
  private String createdDate = null;

  @SerializedName("published_date")
  private String publishedDate = null;

  @SerializedName("material_type_facet")
  private String materialTypeFacet = null;

  @SerializedName("kicker")
  private String kicker = null;

  @SerializedName("des_facet")
  private List<String> desFacet = new ArrayList<String>();

  @SerializedName("org_facet")
  private String orgFacet = null;

  @SerializedName("per_facet")
  private List<String> perFacet = new ArrayList<String>();

  @SerializedName("geo_facet")
  private List<String> geoFacet = new ArrayList<String>();

  @SerializedName("multimedia")
  private List<ArticleMultimedia> multimedia = new ArrayList<ArticleMultimedia>();

  @SerializedName("related_urls")
  private List<ArticleRelatedUrls> relatedUrls = new ArrayList<ArticleRelatedUrls>();

  public Article section(String section) {
    this.section = section;
    return this;
  }

   /**
   * Get section
   * @return section
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSection() {
    return section;
  }

  public void setSection(String section) {
    this.section = section;
  }

  public Article subsection(String subsection) {
    this.subsection = subsection;
    return this;
  }

   /**
   * Get subsection
   * @return subsection
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubsection() {
    return subsection;
  }

  public void setSubsection(String subsection) {
    this.subsection = subsection;
  }

  public Article title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Article _abstract(String _abstract) {
    this._abstract = _abstract;
    return this;
  }

   /**
   * Get _abstract
   * @return _abstract
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAbstract() {
    return _abstract;
  }

  public void setAbstract(String _abstract) {
    this._abstract = _abstract;
  }

  public Article url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Article thumbnailStandard(String thumbnailStandard) {
    this.thumbnailStandard = thumbnailStandard;
    return this;
  }

   /**
   * Get thumbnailStandard
   * @return thumbnailStandard
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThumbnailStandard() {
    return thumbnailStandard;
  }

  public void setThumbnailStandard(String thumbnailStandard) {
    this.thumbnailStandard = thumbnailStandard;
  }

  public Article shortUrl(String shortUrl) {
    this.shortUrl = shortUrl;
    return this;
  }

   /**
   * Get shortUrl
   * @return shortUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShortUrl() {
    return shortUrl;
  }

  public void setShortUrl(String shortUrl) {
    this.shortUrl = shortUrl;
  }

  public Article byline(String byline) {
    this.byline = byline;
    return this;
  }

   /**
   * Get byline
   * @return byline
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getByline() {
    return byline;
  }

  public void setByline(String byline) {
    this.byline = byline;
  }

  public Article itemType(String itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemType() {
    return itemType;
  }

  public void setItemType(String itemType) {
    this.itemType = itemType;
  }

  public Article updatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
    return this;
  }

   /**
   * Get updatedDate
   * @return updatedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUpdatedDate() {
    return updatedDate;
  }

  public void setUpdatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
  }

  public Article createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public Article publishedDate(String publishedDate) {
    this.publishedDate = publishedDate;
    return this;
  }

   /**
   * Get publishedDate
   * @return publishedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPublishedDate() {
    return publishedDate;
  }

  public void setPublishedDate(String publishedDate) {
    this.publishedDate = publishedDate;
  }

  public Article materialTypeFacet(String materialTypeFacet) {
    this.materialTypeFacet = materialTypeFacet;
    return this;
  }

   /**
   * Get materialTypeFacet
   * @return materialTypeFacet
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMaterialTypeFacet() {
    return materialTypeFacet;
  }

  public void setMaterialTypeFacet(String materialTypeFacet) {
    this.materialTypeFacet = materialTypeFacet;
  }

  public Article kicker(String kicker) {
    this.kicker = kicker;
    return this;
  }

   /**
   * Get kicker
   * @return kicker
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKicker() {
    return kicker;
  }

  public void setKicker(String kicker) {
    this.kicker = kicker;
  }

  public Article desFacet(List<String> desFacet) {
    this.desFacet = desFacet;
    return this;
  }

  public Article addDesFacetItem(String desFacetItem) {
    this.desFacet.add(desFacetItem);
    return this;
  }

   /**
   * Get desFacet
   * @return desFacet
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getDesFacet() {
    return desFacet;
  }

  public void setDesFacet(List<String> desFacet) {
    this.desFacet = desFacet;
  }

  public Article orgFacet(String orgFacet) {
    this.orgFacet = orgFacet;
    return this;
  }

   /**
   * Get orgFacet
   * @return orgFacet
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrgFacet() {
    return orgFacet;
  }

  public void setOrgFacet(String orgFacet) {
    this.orgFacet = orgFacet;
  }

  public Article perFacet(List<String> perFacet) {
    this.perFacet = perFacet;
    return this;
  }

  public Article addPerFacetItem(String perFacetItem) {
    this.perFacet.add(perFacetItem);
    return this;
  }

   /**
   * Get perFacet
   * @return perFacet
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getPerFacet() {
    return perFacet;
  }

  public void setPerFacet(List<String> perFacet) {
    this.perFacet = perFacet;
  }

  public Article geoFacet(List<String> geoFacet) {
    this.geoFacet = geoFacet;
    return this;
  }

  public Article addGeoFacetItem(String geoFacetItem) {
    this.geoFacet.add(geoFacetItem);
    return this;
  }

   /**
   * Get geoFacet
   * @return geoFacet
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getGeoFacet() {
    return geoFacet;
  }

  public void setGeoFacet(List<String> geoFacet) {
    this.geoFacet = geoFacet;
  }

  public Article multimedia(List<ArticleMultimedia> multimedia) {
    this.multimedia = multimedia;
    return this;
  }

  public Article addMultimediaItem(ArticleMultimedia multimediaItem) {
    this.multimedia.add(multimediaItem);
    return this;
  }

   /**
   * Get multimedia
   * @return multimedia
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ArticleMultimedia> getMultimedia() {
    return multimedia;
  }

  public void setMultimedia(List<ArticleMultimedia> multimedia) {
    this.multimedia = multimedia;
  }

  public Article relatedUrls(List<ArticleRelatedUrls> relatedUrls) {
    this.relatedUrls = relatedUrls;
    return this;
  }

  public Article addRelatedUrlsItem(ArticleRelatedUrls relatedUrlsItem) {
    this.relatedUrls.add(relatedUrlsItem);
    return this;
  }

   /**
   * Get relatedUrls
   * @return relatedUrls
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ArticleRelatedUrls> getRelatedUrls() {
    return relatedUrls;
  }

  public void setRelatedUrls(List<ArticleRelatedUrls> relatedUrls) {
    this.relatedUrls = relatedUrls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Article article = (Article) o;
    return Objects.equals(this.section, article.section) &&
        Objects.equals(this.subsection, article.subsection) &&
        Objects.equals(this.title, article.title) &&
        Objects.equals(this._abstract, article._abstract) &&
        Objects.equals(this.url, article.url) &&
        Objects.equals(this.thumbnailStandard, article.thumbnailStandard) &&
        Objects.equals(this.shortUrl, article.shortUrl) &&
        Objects.equals(this.byline, article.byline) &&
        Objects.equals(this.itemType, article.itemType) &&
        Objects.equals(this.updatedDate, article.updatedDate) &&
        Objects.equals(this.createdDate, article.createdDate) &&
        Objects.equals(this.publishedDate, article.publishedDate) &&
        Objects.equals(this.materialTypeFacet, article.materialTypeFacet) &&
        Objects.equals(this.kicker, article.kicker) &&
        Objects.equals(this.desFacet, article.desFacet) &&
        Objects.equals(this.orgFacet, article.orgFacet) &&
        Objects.equals(this.perFacet, article.perFacet) &&
        Objects.equals(this.geoFacet, article.geoFacet) &&
        Objects.equals(this.multimedia, article.multimedia) &&
        Objects.equals(this.relatedUrls, article.relatedUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(section, subsection, title, _abstract, url, thumbnailStandard, shortUrl, byline, itemType, updatedDate, createdDate, publishedDate, materialTypeFacet, kicker, desFacet, orgFacet, perFacet, geoFacet, multimedia, relatedUrls);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Article {\n");
    
    sb.append("    section: ").append(toIndentedString(section)).append("\n");
    sb.append("    subsection: ").append(toIndentedString(subsection)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    _abstract: ").append(toIndentedString(_abstract)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    thumbnailStandard: ").append(toIndentedString(thumbnailStandard)).append("\n");
    sb.append("    shortUrl: ").append(toIndentedString(shortUrl)).append("\n");
    sb.append("    byline: ").append(toIndentedString(byline)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    publishedDate: ").append(toIndentedString(publishedDate)).append("\n");
    sb.append("    materialTypeFacet: ").append(toIndentedString(materialTypeFacet)).append("\n");
    sb.append("    kicker: ").append(toIndentedString(kicker)).append("\n");
    sb.append("    desFacet: ").append(toIndentedString(desFacet)).append("\n");
    sb.append("    orgFacet: ").append(toIndentedString(orgFacet)).append("\n");
    sb.append("    perFacet: ").append(toIndentedString(perFacet)).append("\n");
    sb.append("    geoFacet: ").append(toIndentedString(geoFacet)).append("\n");
    sb.append("    multimedia: ").append(toIndentedString(multimedia)).append("\n");
    sb.append("    relatedUrls: ").append(toIndentedString(relatedUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

